### ISSUE TITLE
popup relative to cursor with line = "cursor-%d" is broken for window with borders

### ISSUE THREAD

**Issue by RishabhRD** [nvim-lua/popup.nvim#19]
while using popup.create if 

- line == "cursor+2"

floating window is fine.
![normal_mappings](https://user-images.githubusercontent.com/26287448/133167046-a382c2a3-9975-48aa-b883-938b19d1d1d5.png)

- line == "cursor-4"

floating window has broken borders
![weirdmappints](https://user-images.githubusercontent.com/26287448/133167102-2d6b4150-530e-4323-a995-89990ba6c032.png)

border breaks for ``line = string.format("cursor-%d", x)`` (for all x > 0)

**Comment by filipdutescu** [comment]
I am having the same problem, have you found any solution?

Also trying to make a rename popup haha

**Comment by RishabhRD** [comment]
@filipdutescu not till now... I think this is a bug in plenary.nvim's window/border.lua maybe... someone needs to do a PR I guess :sweat_smile:

**Comment by filipdutescu** [comment]
@RishabhRD I am going to dive into it today, experiment a bit, maybe I can find something. Honestly, unless a fix is easy to find, personally, I think I will go with absolute numbers, for line and column, instead of cursor-relative ones.

**Comment by filipdutescu** [comment]
@RishabhRD I have opened [a PR for `plenary`](https://github.com/nvim-lua/plenary.nvim/pull/240), as shown in the comment history, in case you want to be in the loop with my progress on fixing this issue.

**Comment by RishabhRD** [comment]
@filipdutescu thanks... waiting for getting this into master

**Comment by filipdutescu** [comment]
@RishabhRD my fix was just merged into `master`. Hopefully it resolves your issues as well! I think you should also close this issue, as the `plenary` repo is the new place for bug reporting, as far as I can tell.

**Comment by RishabhRD** [comment]
@filipdutescu thanks! It works like a charm now. Closing the issue.
